### ISSUE TITLE
impossible to catch generated ReferenceError

### ISSUE THREAD

**Issue by damianofalcioni** [Siubaak/sval#105]
Hi,
when the runned code try to access an object that has not been imported it generate a ReferenceError that cannot be catch.
```
ReferenceError: myObj is not defined
    at ...\node_modules\sval\dist\sval.js:1990:21
...
Node.js v20.16.0
npm error Lifecycle script `run` failed with error:
npm error code 1
```
There is a way to handle it? 
I've seen in the code there is a throwErr option but is not exposed.

Thanks

PS: I'm importing Sval as an ES6 module in Node

**Comment by Siubaak** [comment]
what about this?

**Comment by Siubaak** [comment]
What about this? Does it work for your scenario?

```js
const interpreter = new Sval()

try {
  interpreter.run('console.error(myObj)')
} catch (err) {
   console.error('Caught error')
}
```

**Comment by damianofalcioni** [comment]
No, it did not catch

**Comment by Siubaak** [comment]
Could you offer a repo or something to reproduce this bug? It seems I can't reproduce it with sval@0.5.2 on node v20.12.2.

**Comment by damianofalcioni** [comment]
when the code is inside an async it is not catch:
```
try {
  interpreter.run(interpreter.run(`
!async function () {
  console.log(myObj);
}();`));
} catch (e) {
  console.error('err');
}
```

**Comment by Siubaak** [comment]
Right, that's how async behaviours. The async function doesn't run on the current loop, so try catch can't catch the error synchronously. Try to catch the error inside:

```js
import Sval from 'sval';

const interpreter = new Sval();

interpreter.run(`
!async function () {
  try {
    console.log(myObj);
  } catch (e) {
    console.error('err');
  }
}();`);
```
