### ISSUE TITLE
performance issue for 'loop'

### ISSUE THREAD

**Issue by bloody-ux** [Siubaak/sval#12]
For below test case, with `iterations` increasing, the program runs slower and slower.
It seems each iteration needs a re-parsing to execute.

Under node 11.13.0， If `iterations` is 1, it costs `1.74ms`, while `0.225ms` running natively.  If `iterations` is 100000, it costs `1443ms`, while `3.59ms` running natively.

If the code runs natively,  

```
const Sval = require('sval');


const interpreter = new Sval({ ecmaVer: 8, sandBox: true });

interpreter.run(`
var x = 0;
function functionOne() {
  x++;
}

var iterations = 100000;
console.time('Function #1');
for(var i = 0; i < iterations; i++ ){
    functionOne();
};
console.timeEnd('Function #1')

exports.result=x;
`);

console.log(interpreter.exports.result);
```

**Comment by bloody-ux** [comment]
Sval uses generator functions a lot, it is about 5 times slower than regular loop. Meanwhile,  generator polyfill has 3 times performance reduction against ES6 native support.

**Comment by Siubaak** [comment]
yep, I've found the performance issue. currently using generator is the best way to support coroutine. I will try another architecture to improve the performance instead of recursive generators

**Comment by Siubaak** [comment]
temporarily I use the normal function for recursion to improve the performance, avoiding recursive generators. in the future, I may try to compile the code into some kinds of intermediate representation, like webassembly, and use vm written js to execute it.

**Comment by bloody-ux** [comment]
I also considered to use WASM to do opt.

**Comment by Siubaak** [comment]
close. see #31
