### ISSUE TITLE
Arrow function should have isolated scope

### ISSUE THREAD

**Issue by bloody-ux** [Siubaak/sval#14]
A new isolated scope should be created for arrow function, but sval doesn't follow this rule.

Test case:

``` javascript
const Sval = require('sval')

const interpreter = new Sval({ ecmaVer: 8 })

interpreter.run(`
(function x() {
  var y = 'outer-value';

  var arrowFunc = () => {
    var y = 'inner-value';
    console.log('inner', y);
  }

  arrowFunc();
  console.log('outer:', y);
})()
`)

module.exports = 'End'
})()
```

Expected result:
``` bash
"inner"
"inner-value"
"outer:"
"outer-value"
"End"
```

Actual result:

``` bash
"inner"
"inner-value"
"outer:"
"inner-value"
"End"
```

The cause is arrow function should have isolated function scope as regular function, but sval doesn't. 

![image](https://user-images.githubusercontent.com/19991767/56087694-b7085400-5ea2-11e9-954a-f3a79f837af7.png)

Arrow func vs regular func:

- `this` is bound to the one of its creation time.
- can't  be a constructor,  will throw error
- `arguments` is not available
- `yield` expression is not allowed,  means can't be a generator function.

**Comment by Siubaak** [comment]
Fixed
