### ISSUE TITLE
toString method doesn't return correct value for funtion

### ISSUE THREAD

**Issue by bloody-ux** [Siubaak/sval#16]
`Function.prototype.toString` should return original source of the function, but sval returns cooked one.

Test case:

``` javascript
const Sval = require('sval')

const interpreter = new Sval({ ecmaVer: 8 })

interpreter.import({
  getItem: n => new Promise(resolve => setTimeout(resolve, 1500, n))
})

interpreter.run(`
  var f = function() {};
  console.log(f.toString());
  
  var o = {};
  console.log(o.toString());
  
  var arr = [1,2];
  console.log(arr.toString());
  
  exports.end = true;
`)

module.exports = 'End: ' + interpreter.exports.end
```

Expected result: 
``` bash
"function() {}"
"[object Object]"
"1,2"
```

Actual result: 
``` bash
"function () {\r\n                    var args = [];\r\n   …d([tmpGenerator.bind(this)], args));\r\n                }"
"[object Object]"
"1,2"
```

To correct this, we need to override `toString` method for functions, but it will cause another test case failed:

``` javascript
(function(){}).toString === Function.prototype.toString
```

It's a hard decision.

**Comment by bloody-ux** [comment]
By the way, the version of `sval` in playground is out of date, could you upgrade to latest version,  @Siubaak ?

**Comment by Siubaak** [comment]
> By the way, the version of `sval` in playground is out of date, could you upgrade to latest version, @Siubaak ?

it's because the dep of `sval` in runkit is out of date. it seems no way to upgrade until runkit updates itself. I will try to build my own playground instead of runkit later on.

**Comment by Siubaak** [comment]
I don't think it's a good idea to override `toString`, but it seems no better way to fix it. I won't fix the issue, since I can't imagine its real world uses except debug purpose.
