### ISSUE TITLE
It's better to add dist directory to .gitignore

### ISSUE THREAD

**Issue by bloody-ux** [Siubaak/sval#19]
Is there any reason to commit `dist` to git? I think it's better to exclude `dist` folder  from commits.

**Comment by Siubaak** [comment]
I prefer to commit the dist that makes me to draw a release containing the min files, for whom needs to download from github.

but it's improper for arbitrary commits of unstable dist, which I keep doing these days. my bad. so if you want a relative stable version, get it from releases or npm.

**Comment by bloody-ux** [comment]
`dist` will introduce a lot of useless files when diffing. Take `https://github.com/Siubaak/sval/commit/4b92acac05d9aa6db9261ee64eaa4f27e232a530` for example, half of the changes are useless.

**Comment by Siubaak** [comment]
that's true, so in the future, I will just commit when a release drafted

**Comment by Siubaak** [comment]
close. free to reopen if any other issues
