### ISSUE TITLE
[potential issue] Should not use `for... in` to loop array

### ISSUE THREAD

**Issue by bloody-ux** [Siubaak/sval#23]
It's not a good idea to iterate array with [`for... in` ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in#Array_iteration_and_for...in),  the index order is not consistent among all environments.

The issue exists in below code:
![image](https://user-images.githubusercontent.com/19991767/56399704-50a87a80-6282-11e9-88e3-6a1200807e46.png)

![image](https://user-images.githubusercontent.com/19991767/56399723-6e75df80-6282-11e9-9de2-d36412715061.png)

![image](https://user-images.githubusercontent.com/19991767/56399733-80578280-6282-11e9-9878-c6828e16487b.png)

![image](https://user-images.githubusercontent.com/19991767/56399756-9e24e780-6282-11e9-9900-874e1a51d4fd.png)

![image](https://user-images.githubusercontent.com/19991767/56399768-b432a800-6282-11e9-86cc-ab69ac1fe491.png)

![image](https://user-images.githubusercontent.com/19991767/56399786-c57bb480-6282-11e9-8af8-2cc6f877ee38.png)

![image](https://user-images.githubusercontent.com/19991767/56400983-463daf00-6289-11e9-8f7c-57dd957a2544.png)

**Comment by Siubaak** [comment]
I will review it later.

**Comment by Siubaak** [comment]
you're right. good issue
