### ISSUE TITLE
Migrate tests to typescript with `ts-jest`

### ISSUE THREAD

**Issue by bloody-ux** [Siubaak/sval#27]
Test cases are written in javascript and it depends on `dist`, which causes 3 issues:

1. coverage data is not clear for each module, only shows `sval.js`
2. need to run ` start`, before running `test`, and it's easy to forget to run `start` script. 
3. no intellisense support when writing test cases.

I will give a PR later.

**Comment by Siubaak** [comment]
I used ts-jest before but it has some bugs, so I change to use jest directly now. you can check this commit #8e70be and figure out the bug

**Comment by bloody-ux** [comment]
issue 1 can be resolved with this [pr](https://github.com/Siubaak/sval/pull/29)

**Comment by bloody-ux** [comment]
@Siubaak,  because of issue 2, you mentioned ,   I will try to use [umi-test](https://github.com/umijs/umi/tree/master/packages/umi-test).

**Comment by Siubaak** [comment]
try it. but I still would like to use ts-jest, and I will find some way to fix issue 2. umi-test is based on jest and enzyme, so I think the problem will be still there.

**Comment by bloody-ux** [comment]
> try it. but I still would like to use ts-jest, and I will find some way to fix issue 2. umi-test is based on jest and enzyme, so I think the problem will be still there.

`umi-test` can resolve the issue, I just tested and have a new PR. because it uses `babel-jest` instead of `ts-jest`
