### ISSUE TITLE
es6 supported

### ISSUE THREAD

**Issue by Siubaak** [Siubaak/sval#3]
Support all es6 features, like arrow function, let/const declaration, class declaration and so on.

**Comment by Siubaak** [comment]
> Are arrow functions being supported in the current version if I set ecmaVer: 6|2015?
> Didn't find anything in the docs...
> BTW: Keep up the amazing work!!!

So busy these days XD...
Actually the current version supports all es2015 features, excepting generator.
And I now get stuck in supporting the generator.

**Comment by Siubaak** [comment]
I will update the releases soon. Thanks for reminding me.
Once getting generator finished, it could be easy to support the async/await feature, and I will try to get it done this year.

**Comment by sancarn** [comment]
`async`/`await` would make this library super useful. Looking forward to it!

**Comment by Siubaak** [comment]
Version 0.2.0 just released, and async/await function is supported.  Set ecmaVer as 8 or 2018. Free to issue if any bugs. @simonwidjaja  @sancarn
