### ISSUE TITLE
[Discussion] tests should be js or ts extension

### ISSUE THREAD

**Issue by bloody-ux** [Siubaak/sval#33]
I found all tests have ts extension now, it will lead to issues:

1、 vscode extension Jest will not work correctly
2、 Invalid test data provided to test case will report ts error in editor.

![image](https://user-images.githubusercontent.com/19991767/57268558-d3b93580-70b6-11e9-871a-65cc8f76c9ec.png)

**Comment by Siubaak** [comment]
you can use type casting to workaround it

```js
interpreter.import(2 as any)
interpreter.import(true as any)
interpreter.import(Symbol('hello') as any)
```

**Comment by bloody-ux** [comment]
Any reason to use ts file extension?

**Comment by Siubaak** [comment]
no specific reason. you can use js for tests

**Comment by Siubaak** [comment]
closed.
