### ISSUE TITLE
ast is being modified by hoist

### ISSUE THREAD

**Issue by Llorx** [Siubaak/sval#37]
Is there a way to avoid ast modification? Because my code runs pretty slow because of multiple `acorn.parse`, so I created a single ast by running `acorn.parse` one time and run the same ast multiple times. That's what I do in JS-Interpreter and is pretty viable as ast is not modified in any way, but keeping all the state in a different object (which I delete or recycle, depending on situations).

I like this interpreter a lot, but I'm having problems implementing it as it always need a new ast, which I create with another `acorn.parse`, because the ast is modified while running, so here "ast caching" is not viable. This makes this interpreter way way slower than JS-Interpreter (actually sval is way faster when interpreting the JS (about 8 times), but globally is slower if you do a lot of runs with the same code).

**Comment by Llorx** [comment]
I thought into cloning the ast object and hoisting/running after that, but cloning such an object each time is also pretty slow.

I'm thinking on another thing now. `hoist` will simply return a new object instead of modifying the ast. If it has to modify the ast in any way, it has just to create a new item, modify it and return it, and if not, just return the item as-is. This way each `hoist` call can be converted to `ast = hoist(ast, this.scope);` and still be pretty fast without modifying the entire code.

**Comment by Siubaak** [comment]
Yes, sval will modify ast when hoisting, but just move the function declarations to the top of the scope.

After finish compile_ir branch, I will expose APIs for caching the bytecodes. Then you can just parse the code once, get the bytecodes, and run the bytecodes multiple times, like:

```js
const interpreter = new Sval
const bytecodes = interpreter.compile('...')
interpreter.run(bytecodes) // this will skip parsing
```

**Comment by Llorx** [comment]
Fine, what I did right now is adding 2 methods to `Sval`:

```javascript
Sval.prototype.getAST = function (code) {
    var ast = acorn.parse(code, this.options);
    return ast;
};
Sval.prototype.runAST = function (ast, scope) {
    hoist$1(ast, scope || this.scope);
    return evaluate(ast, scope || this.scope);
};
```

Then I just use them like this:

```javascript
let sval = new Sval();
let Scope = sval.scope.constructor; // Hack si I can create scopes on-the-fly depending on context

/* at some point */
var scope = new Scope();
sval.runAST(ast, scope);
```

The scope hack is to run the same ast code in different contexts.

With this exact code running on both JS-Interpreter and Sval, I still see Sval running at half speed when running about 50 thousand repeats (creating new scope and such). I guess that is because on each run a new hoist is made, apart from running the ast. I'm gonna wait for the new branch being finished to continue tests as maybe has more performance improvements at this point.

**Comment by jifeon** [comment]
Hi @Siubaak! 

I think that `runAST` suggested by @Llorx  is a nice feature. In my case, I already have AST and do not want to transform it info string before evaluation. Any chance to have `runAST` function in the lib?

**Comment by Siubaak** [comment]
@jifeon Add support for executing Estree Spec AST by `run` since version 0.4.7

**Comment by jifeon** [comment]
That's amazing! Thank you! 

I have one related question: in my project I have a case where I need to evaluate just part of ast and get result of it. `run` accepts `Program` (`hoist` requires it at least) and can provide output only via `export`. Probably you can give me an advice how can I evaluate part of code and get latest values from the stack?

Currently for MVP I used very hacked solution:

```js
const result = sval.runAST(node).state.shift();
```

where `runAST` skips `hoist`. In near future I will need to rewrite it into more robust solution, so if you can give an advice it would be awesome.
