### ISSUE TITLE
Use meriyah vs acorn

### ISSUE THREAD

**Issue by Llorx** [Siubaak/sval#41]
Meriyah is faster, compiles to the same AST as acorn and also supports future ES specs, so should be easy to move from one to the other.

I think is a good option to move from one to the other: https://github.com/meriyah/meriyah

Benchmarks: https://meriyah.github.io/meriyah/performance/ (cold test fails when reaching jquery mobile because of a 404 error).

EDIT: Just changed acorn to meriyah and works out of the box, without any special addition. One problem is that the `options` object is different, but the performance improvement is incredible.

Maybe we can pass our own "parser" and select meriyah, acorn or even esprima (just pass a `parse` function option which should return an AST tree) or something like that.

PD: I've tested it with my own scripts and works 100%. Meriya has a lot of options disabled by default (like locations and raws) so I don't know what you actually need for it to work 100%.

**Comment by Siubaak** [comment]
cool idea. I will consider about this.

default: acorn
optional: acorn-like parser or esprima

**Comment by Siubaak** [comment]
Add parse method for Sval instance, which allows custom acorn-like parser passed in
