### ISSUE TITLE
Serializable interpreter?

### ISSUE THREAD

**Issue by kefniark** [Siubaak/sval#45]
Hello there,

This library is quite useful, thanks and really a good job.
I was wondering if it's possible with sval to serialize the interpreter, store it, deserialize it later, and resume the execution. Even if there are some limitation, the idea would be to use it like a state machine. It's quite useful for debug and testing (branch, rollback execution, ...)

I know JS interpreter has this feature, but the lack of modern ECMA (es5 only) makes it really hard to use compared to sval.

**Comment by Siubaak** [comment]
Cool idea. Actually I'm working on it. See #31.
