### ISSUE TITLE
Support for dynamic imports of ES modules

### ISSUE THREAD

**Issue by imolorhe** [Siubaak/sval#47]
Hey, nice tool you've got here. I'm using it in a project I'm working on. I was trying to see if I could use the new dynamic imports in the demo jsbin but got an error:

`SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'`.

Do I need to do something special to get it to work? Or is it the environment setup I should be looking at? (since I believe it needs me to use a `<script type="module"></script>`)

**Comment by Siubaak** [comment]
Unfortunately, Sval don't support ES6 module as well as dynamic import. I think you could use webpack to support dynamic import, and pass the import promise to Sval instead, like:

```js
const importPromise = import('xxx')
const interpreter = new Sval
interpreter.import('getSomeModule', importPromise)
interpreter.run(`
    getSomeModule.then(module => {
        // use the module
    })
`)
```

**Comment by imolorhe** [comment]
Thanks for letting me know. I am not sure using webpack would work for my use case, since I want to import the modules via a HTTP URL, rather than a local file (making use of the pika.dev CDN)
