### ISSUE TITLE
小程序热更新问题

### ISSUE THREAD

**Issue by zk320520** [Siubaak/sval#48]
`const Sval = require('sval')
const interpreter = new Sval()

interpreter.import({ Page, wx, app: getApp() })
interprete.run(`
  Page({
    data: {},
    onShow() {},
    customMethod() {}
  })
`)`

小程序使用此方法做热更新时，若脚本字符串为异步获取，需要在此页面打开之前获取到代码，否则会导致页面注册失败、

**Comment by Siubaak** [comment]
是的，你说的对，这是小程序本身的机制，干预不了
