### ISSUE TITLE
Unexpected behaviour with promises (Bug?)

### ISSUE THREAD

**Issue by simonwidjaja** [Siubaak/sval#5]
Hi again.
I am running into a problem when using Promises.
Here are two cases:
```
// Case 1
fs.openFileDialog('template.txt').then(()=>{
  console.log('then');
});    

// Case 2
let promise = fs.openFileDialog('template.txt');
promise.then(()=>{
  console.log('then');
});
```
Case 1 fails. It actually executes the async functions twice (fs.openFileDialog('template.txt')). So I get two open-file-dialogs at once. 

Case 2 works without any problems.

Is this a known bug?
Thanks in advance...

**Comment by Siubaak** [comment]
Temporarily fixed. I'm considering to rewrite it later
