### ISSUE TITLE
Setting time-bound on execution of code

### ISSUE THREAD

**Issue by ghost** [Siubaak/sval#51]
I am looking to use Sval in an educational context and would like to know if there is any way to set a time-bound on how long the evaluated code can run for? This would be helpful if the evaluated code has an infinite loop.

An older project (JS-Interpreter) handles this use case "by calling the step function a maximum number of times, or by calling step indefinitely many times but using a setTimeout between each call to ensure other tasks have a chance to execute". I wonder if there's something I can do in Sval like this?

**Comment by Siubaak** [comment]
Sval has no similar features to restrict the execution time or steps, and I will add this option in the future.

**Comment by gdagrove** [comment]
Thank you, looking forward to the option
