### ISSUE TITLE
循环语句中的switch break会导致出错

### ISSUE THREAD

**Issue by yoyoworms** [Siubaak/sval#54]
遇到switch条件中的break会直接跳出循环，测试代码如下：

`var i = 0;
    while (i < 10) {
        console.log(i);
        i++;
        switch (2) {
            case 2: break;
        }
    }`

只打印 0 即退出。

将 function SwitchStatement 中
`          if (result === BREAK || result === CONTINUE || result === RETURN) {
              return result;
          }`

部分改成

`              if (result === BREAK) {
                  break;
              }
              if (result === CONTINUE || result === RETURN) {
                  return result;
              }`

可破，但是不确定是否会引入其他问题，麻烦更新下。

**Comment by Siubaak** [comment]
正在重构，重构完成后会fix掉这个问题

**Comment by Siubaak** [comment]
Duplicate #42

**Comment by Siubaak** [comment]
@yoyoworms 0.4.7已fix
