### ISSUE TITLE
Module support

### ISSUE THREAD

**Issue by tscpp** [Siubaak/sval#67]
I am working on a desktop simulation for the browser. I would really want module support to be added to sval. I need to import two libraries in my files. I also need the run the files in sandbox. My current workaround is exporting a function to, later on, be called with the modules inside a parameter.

**Comment by Siubaak** [comment]
Have you ever try the API `interpreter.import`?

**Comment by Siubaak** [comment]
Have you ever tried API `interpreter.import`?
