### ISSUE TITLE
Support import and export declarations

### ISSUE THREAD

**Issue by curly210102** [Siubaak/sval#68]
Hope to support ES Module.
acorn supported [`sourceType`](https://github.com/acornjs/acorn/tree/master/acorn#interface) option. Can Sval supports this option or enhance the extensibility of options?

**Comment by TheShermanTanker** [comment]
Any progress on this?

**Comment by Siubaak** [comment]
@curly210102 @TheShermanTanker 

Supported from 0.5.1
