### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by evalPenny** [Siubaak/sval#73]
![Screenshot 2021-06-03 132629](https://user-images.githubusercontent.com/83997151/120586934-659af480-c46f-11eb-8783-cd1197fb3bc2.jpg)

[Code Execution Example](https://codepen.io/khajin1/pen/yLMvZrz)

P.S. if you want to know, I'm on Chrome 90.0.4430.212

**Comment by Siubaak** [comment]
That's a bug of [acorn](https://github.com/acornjs/acorn), used by sval as a parser.
