### ISSUE TITLE
是否有性能数据可以分享？

### ISSUE THREAD

**Issue by liyangready** [Siubaak/sval#74]
是否有性能测试数据可以分享，比如有测试过和原生js性能的差距吗。

**Comment by Siubaak** [comment]
可以说性能差距很大，永远不要对这类解释器的性能抱有希望23333
https://www.v2ex.com/t/553734

**Comment by Siubaak** [comment]
目前在另外一个分支重构实现，性能应该能提高一些，不过暂时没有时间去搞
