### ISSUE TITLE
How to get the result of expression?

### ISSUE THREAD

**Issue by jcubic** [Siubaak/sval#78]
I want to execute:

```javascript
interpreter.run('var x = 10;');
interpreter.run('x');
```

so how to get the output of expression? Note I have no idea what the value is I want to build a REPL. That will work with:

```javascript
interpreter.run('let x = 10;');
interpreter.run('x');
```
because eval runs in strict mode when using let and code is in a block.

**Comment by Siubaak** [comment]
Have you ever tried `exports` to get the output? Did it meet your requirements?

**Comment by jcubic** [comment]
It will not work. If I wrap let with  export it will not be available on next run. This is not how interpreter should work.

**Comment by Siubaak** [comment]
I'm not sure if I get your point. Although Sval isn't for the purpose of building a REPL, you could still get the output of expressions using `exports` as below, to simulate the behavior of REPL:

```js
const interpreter = new Sval()

function repl(expression) {
  try {
    interpreter.run('exports.output = ' + expression)
  } catch (err) {
    interpreter.run(expression)
    interpreter.run('exports.output = undefined')
  }
}

repl('let x = 10')
console.log(interpreter.exports.output) // undefined
repl('x')
console.log(interpreter.exports.output) // 10
repl('x + 1')
console.log(interpreter.exports.output) // 11
```

If I misunderstood, you could give some specific cases for further explanation.

**Comment by jcubic** [comment]
I will not work, because I will need to have separated parser to detect if the value is expression or statement and transplile the code properly. Too bad because this is the only project that suppose to (according to Google) be JavaScript in JavaScript but it's not.

Thanks anyone for you time.
