### ISSUE TITLE
Issues with regex

### ISSUE THREAD

**Issue by AlexandrGuk** [Siubaak/sval#81]
Problems when processing regular expressions.

Simple Javascript code:
```
    const test = 'Hello world 21'  
    console.log(test.match(/\D+/));  // ['Hello world ', index: 0, input: 'Hello world 21', groups: undefined]
    console.log(test.match(/\d+/)); // ['21', index: 12, input: 'Hello world 21', groups: undefined]
```

The same code, when using Sval:

const interpreter = new Sval()
interpreter.run(`
    const test = 'Hello world 21'
    console.log(test.match(/\D+/)); // null
    console.log(test.match(/\d+/)); // ["d"]
`)

**Comment by Siubaak** [comment]
You need to escape *\*

**Comment by Siubaak** [comment]
You need to escape \ char. Try below:
```js
interpreter.run(`
    const test = 'Hello world 21';
    console.log(test.match(/\\D+/));
    console.log(test.match(/\\d+/));
`);
```

**Comment by AlexandrGuk** [comment]
Thanks
