### ISSUE TITLE
Support optional chaining

### ISSUE THREAD

**Issue by dprentis** [Siubaak/sval#83]
Great work!

Was wondering if it would be problematic to add support for optional chaining, which is available in acorn 7.3.0 and newer (https://github.com/acornjs/acorn/issues/1010). I was able to use the acorn parser version 8.7.1, but sval doesn't accept the chaining operator in the generated AST.

**Comment by Siubaak** [comment]
0.5.0 released and support optional chaining and nullish coalescing.
