### ISSUE TITLE
behavior of async code exection

### ISSUE THREAD

**Issue by XDinEuro** [Siubaak/sval#84]
Hi,

I am wondering if the `Sval.run()` can also be a asynchronous call, which means in [playground](https://jsbin.com/kehahiqono/edit?js,console), this log `console.log('End: ' + interpreter.exports.end)` will be printed after the intermiediate print in executed code ,like this 

```
"Sval Version: 0.4.8"
1
2
3
"End: true"
```

If not, is there a way to get the status of the code execution? How can I easily know if the code execution is finished?

**Comment by Siubaak** [comment]
https://jsbin.com/kuzorobuqo/edit?js,console

**Comment by XDinEuro** [comment]
> https://jsbin.com/kuzorobuqo/edit?js,console
> 
> You should callback or emit an event to notify if an async exection finished

thanks, this will solve the issue
